# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DS345Settings_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DS345Settings(object):
    def setupUi(self, DS345Settings):
        DS345Settings.setObjectName("DS345Settings")
        DS345Settings.resize(254, 118)
        self.formLayout = QtWidgets.QFormLayout(DS345Settings)
        self.formLayout.setContentsMargins(0, 2, 0, 2)
        self.formLayout.setSpacing(2)
        self.formLayout.setObjectName("formLayout")
        self.labelFrequency = QtWidgets.QLabel(DS345Settings)
        self.labelFrequency.setObjectName("labelFrequency")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelFrequency)
        self.frequency = QtWidgets.QDoubleSpinBox(DS345Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequency.sizePolicy().hasHeightForWidth())
        self.frequency.setSizePolicy(sizePolicy)
        self.frequency.setDecimals(6)
        self.frequency.setMinimum(1e-05)
        self.frequency.setMaximum(100000.0)
        self.frequency.setProperty("value", 1.0)
        self.frequency.setObjectName("frequency")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frequency)
        self.labelAmplitude = QtWidgets.QLabel(DS345Settings)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelAmplitude)
        self.amplitude = QtWidgets.QDoubleSpinBox(DS345Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amplitude.sizePolicy().hasHeightForWidth())
        self.amplitude.setSizePolicy(sizePolicy)
        self.amplitude.setMinimum(0.0)
        self.amplitude.setMaximum(5.0)
        self.amplitude.setSingleStep(0.1)
        self.amplitude.setProperty("value", 1.0)
        self.amplitude.setObjectName("amplitude")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.amplitude)
        self.labelOffset = QtWidgets.QLabel(DS345Settings)
        self.labelOffset.setObjectName("labelOffset")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelOffset)
        self.offset = QtWidgets.QDoubleSpinBox(DS345Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offset.sizePolicy().hasHeightForWidth())
        self.offset.setSizePolicy(sizePolicy)
        self.offset.setMinimum(-5.0)
        self.offset.setMaximum(5.0)
        self.offset.setSingleStep(0.1)
        self.offset.setObjectName("offset")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.offset)
        self.labelWaveform = QtWidgets.QLabel(DS345Settings)
        self.labelWaveform.setObjectName("labelWaveform")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelWaveform)
        self.waveform = QtWidgets.QComboBox(DS345Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveform.sizePolicy().hasHeightForWidth())
        self.waveform.setSizePolicy(sizePolicy)
        self.waveform.setObjectName("waveform")
        self.waveform.addItem("")
        self.waveform.addItem("")
        self.waveform.addItem("")
        self.waveform.addItem("")
        self.waveform.addItem("")
        self.waveform.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.waveform)

        self.retranslateUi(DS345Settings)
        QtCore.QMetaObject.connectSlotsByName(DS345Settings)

    def retranslateUi(self, DS345Settings):
        _translate = QtCore.QCoreApplication.translate
        DS345Settings.setWindowTitle(_translate("DS345Settings", "DS345"))
        DS345Settings.setStatusTip(_translate("DS345Settings", "DS345: Controls"))
        self.labelFrequency.setText(_translate("DS345Settings", "Frequency"))
        self.frequency.setStatusTip(_translate("DS345Settings", "DS345: Frequency [Hz]"))
        self.frequency.setSuffix(_translate("DS345Settings", " Hz"))
        self.labelAmplitude.setText(_translate("DS345Settings", "Amplitude"))
        self.amplitude.setStatusTip(_translate("DS345Settings", "DS345: Amplitude"))
        self.amplitude.setSuffix(_translate("DS345Settings", " Vpp"))
        self.labelOffset.setText(_translate("DS345Settings", "Offset"))
        self.offset.setStatusTip(_translate("DS345Settings", "DS345: Offset"))
        self.offset.setSuffix(_translate("DS345Settings", " V"))
        self.labelWaveform.setText(_translate("DS345Settings", "Waveform"))
        self.waveform.setStatusTip(_translate("DS345Settings", "DS345: Waveform"))
        self.waveform.setItemText(0, _translate("DS345Settings", "sine"))
        self.waveform.setItemText(1, _translate("DS345Settings", "square"))
        self.waveform.setItemText(2, _translate("DS345Settings", "triangle"))
        self.waveform.setItemText(3, _translate("DS345Settings", "ramp"))
        self.waveform.setItemText(4, _translate("DS345Settings", "noise"))
        self.waveform.setItemText(5, _translate("DS345Settings", "arbitrary"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DS345Settings = QtWidgets.QWidget()
    ui = Ui_DS345Settings()
    ui.setupUi(DS345Settings)
    DS345Settings.show()
    sys.exit(app.exec_())

