# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Polargraph_UI.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Polargraph(object):
    def setupUi(self, Polargraph):
        Polargraph.setObjectName("Polargraph")
        Polargraph.resize(333, 265)
        Polargraph.setMinimumSize(QtCore.QSize(333, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Polargraph)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupSetup = QtWidgets.QGroupBox(Polargraph)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupSetup.setFont(font)
        self.groupSetup.setObjectName("groupSetup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupSetup)
        self.gridLayout_3.setContentsMargins(4, 2, 4, 2)
        self.gridLayout_3.setHorizontalSpacing(4)
        self.gridLayout_3.setVerticalSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelEll = QtWidgets.QLabel(self.groupSetup)
        self.labelEll.setObjectName("labelEll")
        self.gridLayout_3.addWidget(self.labelEll, 0, 0, 1, 1)
        self.ell = QtWidgets.QDoubleSpinBox(self.groupSetup)
        self.ell.setMinimum(0.1)
        self.ell.setMaximum(10.0)
        self.ell.setSingleStep(0.01)
        self.ell.setProperty("value", 1.0)
        self.ell.setObjectName("ell")
        self.gridLayout_3.addWidget(self.ell, 0, 1, 1, 1)
        self.labely0 = QtWidgets.QLabel(self.groupSetup)
        self.labely0.setObjectName("labely0")
        self.gridLayout_3.addWidget(self.labely0, 0, 2, 1, 1)
        self.y0 = QtWidgets.QDoubleSpinBox(self.groupSetup)
        self.y0.setDecimals(3)
        self.y0.setMinimum(0.01)
        self.y0.setMaximum(1.0)
        self.y0.setSingleStep(0.01)
        self.y0.setProperty("value", 0.1)
        self.y0.setObjectName("y0")
        self.gridLayout_3.addWidget(self.y0, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupSetup)
        self.groupBelt = QtWidgets.QGroupBox(Polargraph)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBelt.setFont(font)
        self.groupBelt.setObjectName("groupBelt")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBelt)
        self.gridLayout_2.setContentsMargins(4, 2, 4, 2)
        self.gridLayout_2.setHorizontalSpacing(4)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelUnit = QtWidgets.QLabel(self.groupBelt)
        self.labelUnit.setObjectName("labelUnit")
        self.gridLayout_2.addWidget(self.labelUnit, 0, 0, 1, 1)
        self.unit = QtWidgets.QDoubleSpinBox(self.groupBelt)
        self.unit.setMinimum(1.0)
        self.unit.setMaximum(5.0)
        self.unit.setSingleStep(0.1)
        self.unit.setProperty("value", 2.0)
        self.unit.setObjectName("unit")
        self.gridLayout_2.addWidget(self.unit, 0, 1, 1, 2)
        self.labelCircum = QtWidgets.QLabel(self.groupBelt)
        self.labelCircum.setObjectName("labelCircum")
        self.gridLayout_2.addWidget(self.labelCircum, 0, 3, 1, 1)
        self.circumference = QtWidgets.QDoubleSpinBox(self.groupBelt)
        self.circumference.setDecimals(0)
        self.circumference.setMinimum(1.0)
        self.circumference.setProperty("value", 25.0)
        self.circumference.setObjectName("circumference")
        self.gridLayout_2.addWidget(self.circumference, 0, 4, 1, 1)
        self.labelSteps = QtWidgets.QLabel(self.groupBelt)
        self.labelSteps.setObjectName("labelSteps")
        self.gridLayout_2.addWidget(self.labelSteps, 1, 0, 1, 2)
        self.steps = QtWidgets.QDoubleSpinBox(self.groupBelt)
        self.steps.setDecimals(0)
        self.steps.setMinimum(100.0)
        self.steps.setMaximum(500.0)
        self.steps.setSingleStep(50.0)
        self.steps.setProperty("value", 200.0)
        self.steps.setObjectName("steps")
        self.gridLayout_2.addWidget(self.steps, 1, 2, 1, 1)
        self.labelStepSpeed = QtWidgets.QLabel(self.groupBelt)
        self.labelStepSpeed.setObjectName("labelStepSpeed")
        self.gridLayout_2.addWidget(self.labelStepSpeed, 1, 3, 1, 1)
        self.stepSpeed = QtWidgets.QDoubleSpinBox(self.groupBelt)
        self.stepSpeed.setDecimals(0)
        self.stepSpeed.setMinimum(10.0)
        self.stepSpeed.setMaximum(1000.0)
        self.stepSpeed.setSingleStep(10.0)
        self.stepSpeed.setProperty("value", 500.0)
        self.stepSpeed.setObjectName("stepSpeed")
        self.gridLayout_2.addWidget(self.stepSpeed, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBelt)
        self.groupScan = QtWidgets.QGroupBox(Polargraph)
        self.groupScan.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupScan.setFont(font)
        self.groupScan.setObjectName("groupScan")
        self.gridLayout = QtWidgets.QGridLayout(self.groupScan)
        self.gridLayout.setContentsMargins(4, 2, 4, 2)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.gotocenter = QtWidgets.QPushButton(self.groupScan)
        self.gotocenter.setObjectName("gotocenter")
        self.gridLayout.addWidget(self.gotocenter, 0, 0, 1, 2)
        self.gotohome = QtWidgets.QPushButton(self.groupScan)
        self.gotohome.setObjectName("gotohome")
        self.gridLayout.addWidget(self.gotohome, 0, 2, 1, 2)
        self.labelX1 = QtWidgets.QLabel(self.groupScan)
        self.labelX1.setObjectName("labelX1")
        self.gridLayout.addWidget(self.labelX1, 1, 0, 1, 1)
        self.x1 = QtWidgets.QDoubleSpinBox(self.groupScan)
        self.x1.setMinimum(-1.0)
        self.x1.setMaximum(1.0)
        self.x1.setSingleStep(0.01)
        self.x1.setObjectName("x1")
        self.gridLayout.addWidget(self.x1, 1, 1, 1, 1)
        self.labelY1 = QtWidgets.QLabel(self.groupScan)
        self.labelY1.setObjectName("labelY1")
        self.gridLayout.addWidget(self.labelY1, 1, 2, 1, 1)
        self.y1 = QtWidgets.QDoubleSpinBox(self.groupScan)
        self.y1.setMinimum(0.0)
        self.y1.setMaximum(1.0)
        self.y1.setSingleStep(0.01)
        self.y1.setObjectName("y1")
        self.gridLayout.addWidget(self.y1, 1, 3, 1, 1)
        self.labelWidth = QtWidgets.QLabel(self.groupScan)
        self.labelWidth.setObjectName("labelWidth")
        self.gridLayout.addWidget(self.labelWidth, 2, 0, 1, 1)
        self.width = QtWidgets.QDoubleSpinBox(self.groupScan)
        self.width.setMinimum(0.05)
        self.width.setMaximum(10.0)
        self.width.setSingleStep(0.01)
        self.width.setProperty("value", 0.6)
        self.width.setObjectName("width")
        self.gridLayout.addWidget(self.width, 2, 1, 1, 1)
        self.labelHeight = QtWidgets.QLabel(self.groupScan)
        self.labelHeight.setObjectName("labelHeight")
        self.gridLayout.addWidget(self.labelHeight, 2, 2, 1, 1)
        self.height = QtWidgets.QDoubleSpinBox(self.groupScan)
        self.height.setMinimum(0.05)
        self.height.setMaximum(10.0)
        self.height.setSingleStep(0.01)
        self.height.setProperty("value", 0.6)
        self.height.setObjectName("height")
        self.gridLayout.addWidget(self.height, 2, 3, 1, 1)
        self.labelSpeed = QtWidgets.QLabel(self.groupScan)
        self.labelSpeed.setObjectName("labelSpeed")
        self.gridLayout.addWidget(self.labelSpeed, 3, 0, 1, 1)
        self.speed = QtWidgets.QDoubleSpinBox(self.groupScan)
        self.speed.setDecimals(0)
        self.speed.setMinimum(1.0)
        self.speed.setMaximum(200.0)
        self.speed.setSingleStep(1.0)
        self.speed.setProperty("value", 20.0)
        self.speed.setObjectName("speed")
        self.gridLayout.addWidget(self.speed, 3, 1, 1, 1)
        self.labelDy = QtWidgets.QLabel(self.groupScan)
        self.labelDy.setObjectName("labelDy")
        self.gridLayout.addWidget(self.labelDy, 3, 2, 1, 1)
        self.dy = QtWidgets.QDoubleSpinBox(self.groupScan)
        self.dy.setDecimals(3)
        self.dy.setMinimum(0.001)
        self.dy.setMaximum(0.5)
        self.dy.setSingleStep(0.001)
        self.dy.setProperty("value", 0.005)
        self.dy.setObjectName("dy")
        self.gridLayout.addWidget(self.dy, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupScan)
        self.labelEll.setBuddy(self.ell)
        self.labely0.setBuddy(self.y0)
        self.labelUnit.setBuddy(self.unit)
        self.labelCircum.setBuddy(self.circumference)
        self.labelSteps.setBuddy(self.steps)
        self.labelStepSpeed.setBuddy(self.stepSpeed)
        self.labelX1.setBuddy(self.x1)
        self.labelY1.setBuddy(self.y1)
        self.labelWidth.setBuddy(self.width)
        self.labelHeight.setBuddy(self.height)
        self.labelSpeed.setBuddy(self.speed)
        self.labelDy.setBuddy(self.dy)

        self.retranslateUi(Polargraph)
        QtCore.QMetaObject.connectSlotsByName(Polargraph)
        Polargraph.setTabOrder(self.ell, self.y0)
        Polargraph.setTabOrder(self.y0, self.unit)
        Polargraph.setTabOrder(self.unit, self.circumference)
        Polargraph.setTabOrder(self.circumference, self.steps)
        Polargraph.setTabOrder(self.steps, self.stepSpeed)
        Polargraph.setTabOrder(self.stepSpeed, self.x1)
        Polargraph.setTabOrder(self.x1, self.y1)
        Polargraph.setTabOrder(self.y1, self.width)
        Polargraph.setTabOrder(self.width, self.height)
        Polargraph.setTabOrder(self.height, self.speed)
        Polargraph.setTabOrder(self.speed, self.dy)

    def retranslateUi(self, Polargraph):
        _translate = QtCore.QCoreApplication.translate
        Polargraph.setWindowTitle(_translate("Polargraph", "Polargraph"))
        self.groupSetup.setTitle(_translate("Polargraph", "Setup"))
        self.labelEll.setText(_translate("Polargraph", "L"))
        self.ell.setSuffix(_translate("Polargraph", " m"))
        self.labely0.setText(_translate("Polargraph", "<html><head/><body><p>y<span style=\" vertical-align:sub;\">0</span></p></body></html>"))
        self.y0.setSuffix(_translate("Polargraph", " m"))
        self.groupBelt.setTitle(_translate("Polargraph", "Belt Drive"))
        self.labelUnit.setText(_translate("Polargraph", "unit"))
        self.unit.setStatusTip(_translate("Polargraph", "Polargraph: Tooth size on timing belt"))
        self.unit.setSuffix(_translate("Polargraph", " mm"))
        self.labelCircum.setText(_translate("Polargraph", "circum"))
        self.circumference.setStatusTip(_translate("Polargraph", "Polargraph: Units per motor revolution"))
        self.circumference.setSuffix(_translate("Polargraph", " units"))
        self.labelSteps.setText(_translate("Polargraph", "steps"))
        self.steps.setStatusTip(_translate("Polargraph", "Polargraph: Motor steps per revolution"))
        self.labelStepSpeed.setText(_translate("Polargraph", "speed"))
        self.stepSpeed.setStatusTip(_translate("Polargraph", "Polargraph: Motor steps per second"))
        self.stepSpeed.setSuffix(_translate("Polargraph", " steps/s"))
        self.groupScan.setTitle(_translate("Polargraph", "Scan"))
        self.gotocenter.setText(_translate("Polargraph", "Center"))
        self.gotohome.setText(_translate("Polargraph", "Home"))
        self.labelX1.setText(_translate("Polargraph", "x1"))
        self.x1.setSuffix(_translate("Polargraph", " m"))
        self.labelY1.setText(_translate("Polargraph", "y1"))
        self.y1.setSuffix(_translate("Polargraph", " m"))
        self.labelWidth.setText(_translate("Polargraph", "width"))
        self.width.setSuffix(_translate("Polargraph", " m"))
        self.labelHeight.setText(_translate("Polargraph", "height"))
        self.height.setSuffix(_translate("Polargraph", " m"))
        self.labelSpeed.setStatusTip(_translate("Polargraph", "Polargraph: Translation speed"))
        self.labelSpeed.setText(_translate("Polargraph", "speed"))
        self.speed.setSuffix(_translate("Polargraph", " mm/s"))
        self.labelDy.setText(_translate("Polargraph", "Δy"))
        self.dy.setSuffix(_translate("Polargraph", " m"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Polargraph = QtWidgets.QWidget()
    ui = Ui_Polargraph()
    ui.setupUi(Polargraph)
    Polargraph.show()
    sys.exit(app.exec_())

