# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SR830Settings_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SR830Settings(object):
    def setupUi(self, SR830Settings):
        SR830Settings.setObjectName("SR830Settings")
        SR830Settings.resize(277, 454)
        SR830Settings.setMinimumSize(QtCore.QSize(277, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(SR830Settings)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupInput = QtWidgets.QGroupBox(SR830Settings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupInput.setFont(font)
        self.groupInput.setObjectName("groupInput")
        self.gridLayout = QtWidgets.QGridLayout(self.groupInput)
        self.gridLayout.setContentsMargins(4, 2, 4, 2)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.labelLineFilter = QtWidgets.QLabel(self.groupInput)
        self.labelLineFilter.setObjectName("labelLineFilter")
        self.gridLayout.addWidget(self.labelLineFilter, 8, 0, 1, 2)
        self.filter = QtWidgets.QComboBox(self.groupInput)
        self.filter.setObjectName("filter")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.gridLayout.addWidget(self.filter, 8, 2, 1, 1)
        self.labelSlope = QtWidgets.QLabel(self.groupInput)
        self.labelSlope.setObjectName("labelSlope")
        self.gridLayout.addWidget(self.labelSlope, 4, 0, 1, 1)
        self.labelCoupling = QtWidgets.QLabel(self.groupInput)
        self.labelCoupling.setObjectName("labelCoupling")
        self.gridLayout.addWidget(self.labelCoupling, 2, 0, 1, 1)
        self.labelSensitivity = QtWidgets.QLabel(self.groupInput)
        self.labelSensitivity.setObjectName("labelSensitivity")
        self.gridLayout.addWidget(self.labelSensitivity, 6, 0, 1, 2)
        self.synchronous = QtWidgets.QComboBox(self.groupInput)
        self.synchronous.setObjectName("synchronous")
        self.synchronous.addItem("")
        self.synchronous.addItem("")
        self.gridLayout.addWidget(self.synchronous, 5, 2, 1, 1)
        self.coupling = QtWidgets.QComboBox(self.groupInput)
        self.coupling.setObjectName("coupling")
        self.coupling.addItem("")
        self.coupling.addItem("")
        self.gridLayout.addWidget(self.coupling, 2, 2, 1, 1)
        self.sensitivity = QtWidgets.QComboBox(self.groupInput)
        self.sensitivity.setObjectName("sensitivity")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.sensitivity.addItem("")
        self.gridLayout.addWidget(self.sensitivity, 6, 2, 1, 1)
        self.labelInput = QtWidgets.QLabel(self.groupInput)
        self.labelInput.setObjectName("labelInput")
        self.gridLayout.addWidget(self.labelInput, 0, 0, 1, 1)
        self.reserve = QtWidgets.QComboBox(self.groupInput)
        self.reserve.setObjectName("reserve")
        self.reserve.addItem("")
        self.reserve.addItem("")
        self.reserve.addItem("")
        self.gridLayout.addWidget(self.reserve, 7, 2, 1, 1)
        self.labelTimeConstant = QtWidgets.QLabel(self.groupInput)
        self.labelTimeConstant.setObjectName("labelTimeConstant")
        self.gridLayout.addWidget(self.labelTimeConstant, 3, 0, 1, 1)
        self.labelSynchronous = QtWidgets.QLabel(self.groupInput)
        self.labelSynchronous.setObjectName("labelSynchronous")
        self.gridLayout.addWidget(self.labelSynchronous, 5, 0, 1, 2)
        self.grounding = QtWidgets.QComboBox(self.groupInput)
        self.grounding.setObjectName("grounding")
        self.grounding.addItem("")
        self.grounding.addItem("")
        self.gridLayout.addWidget(self.grounding, 1, 2, 1, 1)
        self.slope = QtWidgets.QComboBox(self.groupInput)
        self.slope.setObjectName("slope")
        self.slope.addItem("")
        self.slope.addItem("")
        self.slope.addItem("")
        self.slope.addItem("")
        self.gridLayout.addWidget(self.slope, 4, 2, 1, 1)
        self.timeConstant = QtWidgets.QComboBox(self.groupInput)
        self.timeConstant.setObjectName("timeConstant")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.timeConstant.addItem("")
        self.gridLayout.addWidget(self.timeConstant, 3, 2, 1, 1)
        self.input = QtWidgets.QComboBox(self.groupInput)
        self.input.setObjectName("input")
        self.input.addItem("")
        self.input.addItem("")
        self.input.addItem("")
        self.input.addItem("")
        self.gridLayout.addWidget(self.input, 0, 2, 1, 1)
        self.labelGrounding = QtWidgets.QLabel(self.groupInput)
        self.labelGrounding.setObjectName("labelGrounding")
        self.gridLayout.addWidget(self.labelGrounding, 1, 0, 1, 2)
        self.labelReserve = QtWidgets.QLabel(self.groupInput)
        self.labelReserve.setObjectName("labelReserve")
        self.gridLayout.addWidget(self.labelReserve, 7, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupInput)
        self.groupAuto = QtWidgets.QGroupBox(SR830Settings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupAuto.setFont(font)
        self.groupAuto.setObjectName("groupAuto")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupAuto)
        self.horizontalLayout_2.setContentsMargins(4, 2, 4, 2)
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.autoGain = QtWidgets.QPushButton(self.groupAuto)
        self.autoGain.setObjectName("autoGain")
        self.horizontalLayout_2.addWidget(self.autoGain)
        self.autoReserve = QtWidgets.QPushButton(self.groupAuto)
        self.autoReserve.setObjectName("autoReserve")
        self.horizontalLayout_2.addWidget(self.autoReserve)
        self.autoPhase = QtWidgets.QPushButton(self.groupAuto)
        self.autoPhase.setObjectName("autoPhase")
        self.horizontalLayout_2.addWidget(self.autoPhase)
        self.verticalLayout.addWidget(self.groupAuto)
        self.groupReference = QtWidgets.QGroupBox(SR830Settings)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupReference.setFont(font)
        self.groupReference.setObjectName("groupReference")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupReference)
        self.gridLayout_2.setContentsMargins(4, 2, 4, 2)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelSource = QtWidgets.QLabel(self.groupReference)
        self.labelSource.setObjectName("labelSource")
        self.gridLayout_2.addWidget(self.labelSource, 0, 0, 1, 1)
        self.labelFrequency = QtWidgets.QLabel(self.groupReference)
        self.labelFrequency.setObjectName("labelFrequency")
        self.gridLayout_2.addWidget(self.labelFrequency, 2, 0, 1, 1)
        self.labelAmplitude = QtWidgets.QLabel(self.groupReference)
        self.labelAmplitude.setObjectName("labelAmplitude")
        self.gridLayout_2.addWidget(self.labelAmplitude, 4, 0, 1, 1)
        self.labelTrigger = QtWidgets.QLabel(self.groupReference)
        self.labelTrigger.setObjectName("labelTrigger")
        self.gridLayout_2.addWidget(self.labelTrigger, 6, 0, 1, 1)
        self.trigger = QtWidgets.QComboBox(self.groupReference)
        self.trigger.setObjectName("trigger")
        self.trigger.addItem("")
        self.trigger.addItem("")
        self.trigger.addItem("")
        self.gridLayout_2.addWidget(self.trigger, 6, 1, 1, 1)
        self.labelPhase = QtWidgets.QLabel(self.groupReference)
        self.labelPhase.setObjectName("labelPhase")
        self.gridLayout_2.addWidget(self.labelPhase, 7, 0, 1, 1)
        self.source = QtWidgets.QComboBox(self.groupReference)
        self.source.setObjectName("source")
        self.source.addItem("")
        self.source.addItem("")
        self.gridLayout_2.addWidget(self.source, 0, 1, 1, 1)
        self.frequency = QtWidgets.QDoubleSpinBox(self.groupReference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequency.sizePolicy().hasHeightForWidth())
        self.frequency.setSizePolicy(sizePolicy)
        self.frequency.setDecimals(3)
        self.frequency.setMinimum(0.001)
        self.frequency.setMaximum(102000.0)
        self.frequency.setProperty("value", 1.0)
        self.frequency.setObjectName("frequency")
        self.gridLayout_2.addWidget(self.frequency, 2, 1, 1, 1)
        self.amplitude = QtWidgets.QDoubleSpinBox(self.groupReference)
        self.amplitude.setDecimals(3)
        self.amplitude.setMinimum(0.004)
        self.amplitude.setMaximum(2.5)
        self.amplitude.setSingleStep(0.1)
        self.amplitude.setProperty("value", 1.0)
        self.amplitude.setObjectName("amplitude")
        self.gridLayout_2.addWidget(self.amplitude, 4, 1, 1, 1)
        self.phase = QtWidgets.QDoubleSpinBox(self.groupReference)
        self.phase.setMinimum(-360.0)
        self.phase.setMaximum(729.99)
        self.phase.setObjectName("phase")
        self.gridLayout_2.addWidget(self.phase, 7, 1, 1, 1)
        self.harmonic = QtWidgets.QSpinBox(self.groupReference)
        self.harmonic.setMinimum(1)
        self.harmonic.setMaximum(19999)
        self.harmonic.setObjectName("harmonic")
        self.gridLayout_2.addWidget(self.harmonic, 8, 1, 1, 1)
        self.labelHarmonic = QtWidgets.QLabel(self.groupReference)
        self.labelHarmonic.setObjectName("labelHarmonic")
        self.gridLayout_2.addWidget(self.labelHarmonic, 8, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupReference)
        self.labelLineFilter.setBuddy(self.filter)
        self.labelSlope.setBuddy(self.slope)
        self.labelCoupling.setBuddy(self.coupling)
        self.labelSensitivity.setBuddy(self.sensitivity)
        self.labelInput.setBuddy(self.input)
        self.labelTimeConstant.setBuddy(self.timeConstant)
        self.labelSynchronous.setBuddy(self.synchronous)
        self.labelGrounding.setBuddy(self.grounding)
        self.labelReserve.setBuddy(self.reserve)
        self.labelSource.setBuddy(self.source)
        self.labelFrequency.setBuddy(self.frequency)
        self.labelAmplitude.setBuddy(self.amplitude)
        self.labelTrigger.setBuddy(self.trigger)
        self.labelPhase.setBuddy(self.phase)
        self.labelHarmonic.setBuddy(self.harmonic)

        self.retranslateUi(SR830Settings)
        QtCore.QMetaObject.connectSlotsByName(SR830Settings)
        SR830Settings.setTabOrder(self.input, self.grounding)
        SR830Settings.setTabOrder(self.grounding, self.coupling)
        SR830Settings.setTabOrder(self.coupling, self.timeConstant)
        SR830Settings.setTabOrder(self.timeConstant, self.slope)
        SR830Settings.setTabOrder(self.slope, self.synchronous)
        SR830Settings.setTabOrder(self.synchronous, self.sensitivity)
        SR830Settings.setTabOrder(self.sensitivity, self.reserve)
        SR830Settings.setTabOrder(self.reserve, self.filter)
        SR830Settings.setTabOrder(self.filter, self.autoGain)
        SR830Settings.setTabOrder(self.autoGain, self.autoReserve)
        SR830Settings.setTabOrder(self.autoReserve, self.autoPhase)
        SR830Settings.setTabOrder(self.autoPhase, self.source)
        SR830Settings.setTabOrder(self.source, self.frequency)
        SR830Settings.setTabOrder(self.frequency, self.amplitude)
        SR830Settings.setTabOrder(self.amplitude, self.trigger)
        SR830Settings.setTabOrder(self.trigger, self.phase)
        SR830Settings.setTabOrder(self.phase, self.harmonic)

    def retranslateUi(self, SR830Settings):
        _translate = QtCore.QCoreApplication.translate
        SR830Settings.setWindowTitle(_translate("SR830Settings", "SR830"))
        self.groupInput.setTitle(_translate("SR830Settings", "Input Configuration"))
        self.labelLineFilter.setText(_translate("SR830Settings", "Line Filter"))
        self.filter.setItemText(0, _translate("SR830Settings", "No Filter"))
        self.filter.setItemText(1, _translate("SR830Settings", "Line Notch"))
        self.filter.setItemText(2, _translate("SR830Settings", "2x Line Notch"))
        self.filter.setItemText(3, _translate("SR830Settings", "Both"))
        self.labelSlope.setText(_translate("SR830Settings", "Slope"))
        self.labelCoupling.setText(_translate("SR830Settings", "Coupling"))
        self.labelSensitivity.setText(_translate("SR830Settings", "Sensitivity"))
        self.synchronous.setItemText(0, _translate("SR830Settings", "Filter Off"))
        self.synchronous.setItemText(1, _translate("SR830Settings", "Filter On"))
        self.coupling.setItemText(0, _translate("SR830Settings", "AC Coupling"))
        self.coupling.setItemText(1, _translate("SR830Settings", "DC Coupling"))
        self.sensitivity.setItemText(0, _translate("SR830Settings", "2 nV/fA"))
        self.sensitivity.setItemText(1, _translate("SR830Settings", "5 nV/fA"))
        self.sensitivity.setItemText(2, _translate("SR830Settings", "10 nV/fA"))
        self.sensitivity.setItemText(3, _translate("SR830Settings", "20 nV/fA"))
        self.sensitivity.setItemText(4, _translate("SR830Settings", "50 nV/fA"))
        self.sensitivity.setItemText(5, _translate("SR830Settings", "100 nV/fA"))
        self.sensitivity.setItemText(6, _translate("SR830Settings", "200 nV/fA"))
        self.sensitivity.setItemText(7, _translate("SR830Settings", "500 nV/fA"))
        self.sensitivity.setItemText(8, _translate("SR830Settings", "1 µV/pA"))
        self.sensitivity.setItemText(9, _translate("SR830Settings", "2 µV/pA"))
        self.sensitivity.setItemText(10, _translate("SR830Settings", "5 µV/pA"))
        self.sensitivity.setItemText(11, _translate("SR830Settings", "10 µV/pA"))
        self.sensitivity.setItemText(12, _translate("SR830Settings", "20 µV/pA"))
        self.sensitivity.setItemText(13, _translate("SR830Settings", "50 µV/pA"))
        self.sensitivity.setItemText(14, _translate("SR830Settings", "100 µV/pA"))
        self.sensitivity.setItemText(15, _translate("SR830Settings", "200 µV/pA"))
        self.sensitivity.setItemText(16, _translate("SR830Settings", "500 µV/pA"))
        self.sensitivity.setItemText(17, _translate("SR830Settings", "1 mV/nA"))
        self.sensitivity.setItemText(18, _translate("SR830Settings", "2 mV/nA"))
        self.sensitivity.setItemText(19, _translate("SR830Settings", "5 mV/nA"))
        self.sensitivity.setItemText(20, _translate("SR830Settings", "10 mV/nA"))
        self.sensitivity.setItemText(21, _translate("SR830Settings", "20 mV/nA"))
        self.sensitivity.setItemText(22, _translate("SR830Settings", "50 mV/nA"))
        self.sensitivity.setItemText(23, _translate("SR830Settings", "100 mV/nA"))
        self.sensitivity.setItemText(24, _translate("SR830Settings", "200 mV/nA"))
        self.sensitivity.setItemText(25, _translate("SR830Settings", "500 mV/nA"))
        self.sensitivity.setItemText(26, _translate("SR830Settings", "1 V/µA"))
        self.labelInput.setText(_translate("SR830Settings", "Input"))
        self.reserve.setItemText(0, _translate("SR830Settings", "High"))
        self.reserve.setItemText(1, _translate("SR830Settings", "Normal"))
        self.reserve.setItemText(2, _translate("SR830Settings", "Low Noise"))
        self.labelTimeConstant.setText(_translate("SR830Settings", "Time Constant"))
        self.labelSynchronous.setText(_translate("SR830Settings", "Synchronous"))
        self.grounding.setItemText(0, _translate("SR830Settings", "Shield Floating"))
        self.grounding.setItemText(1, _translate("SR830Settings", "Shield Grounded"))
        self.slope.setItemText(0, _translate("SR830Settings", "6 dB/oct"))
        self.slope.setItemText(1, _translate("SR830Settings", "12 dB/oct"))
        self.slope.setItemText(2, _translate("SR830Settings", "18 dB/oct"))
        self.slope.setItemText(3, _translate("SR830Settings", "24 dB/oct"))
        self.timeConstant.setItemText(0, _translate("SR830Settings", "10 µs"))
        self.timeConstant.setItemText(1, _translate("SR830Settings", "30 µs"))
        self.timeConstant.setItemText(2, _translate("SR830Settings", "100 µs"))
        self.timeConstant.setItemText(3, _translate("SR830Settings", "300 µs"))
        self.timeConstant.setItemText(4, _translate("SR830Settings", "1 ms"))
        self.timeConstant.setItemText(5, _translate("SR830Settings", "3 ms"))
        self.timeConstant.setItemText(6, _translate("SR830Settings", "10 ms"))
        self.timeConstant.setItemText(7, _translate("SR830Settings", "30 ms"))
        self.timeConstant.setItemText(8, _translate("SR830Settings", "100 ms"))
        self.timeConstant.setItemText(9, _translate("SR830Settings", "300 ms"))
        self.timeConstant.setItemText(10, _translate("SR830Settings", "1 s"))
        self.timeConstant.setItemText(11, _translate("SR830Settings", "3 s"))
        self.timeConstant.setItemText(12, _translate("SR830Settings", "10 s"))
        self.timeConstant.setItemText(13, _translate("SR830Settings", "30 s"))
        self.timeConstant.setItemText(14, _translate("SR830Settings", "100 s"))
        self.timeConstant.setItemText(15, _translate("SR830Settings", "300 s"))
        self.timeConstant.setItemText(16, _translate("SR830Settings", "1 ks"))
        self.timeConstant.setItemText(17, _translate("SR830Settings", "3 ks"))
        self.timeConstant.setItemText(18, _translate("SR830Settings", "10 ks"))
        self.timeConstant.setItemText(19, _translate("SR830Settings", "30 ks"))
        self.input.setItemText(0, _translate("SR830Settings", "A"))
        self.input.setItemText(1, _translate("SR830Settings", "A-B"))
        self.input.setItemText(2, _translate("SR830Settings", "I (1 MOhm)"))
        self.input.setItemText(3, _translate("SR830Settings", "I (100 MOhm)"))
        self.labelGrounding.setText(_translate("SR830Settings", "Grounding"))
        self.labelReserve.setText(_translate("SR830Settings", "Reserve"))
        self.groupAuto.setTitle(_translate("SR830Settings", "Auto"))
        self.autoGain.setText(_translate("SR830Settings", "Gain"))
        self.autoReserve.setText(_translate("SR830Settings", "Reserve"))
        self.autoPhase.setText(_translate("SR830Settings", "Phase"))
        self.groupReference.setTitle(_translate("SR830Settings", "Reference"))
        self.labelSource.setText(_translate("SR830Settings", "Source"))
        self.labelFrequency.setText(_translate("SR830Settings", "Frequency "))
        self.labelAmplitude.setText(_translate("SR830Settings", "Amplitude"))
        self.labelTrigger.setText(_translate("SR830Settings", "Trigger"))
        self.trigger.setItemText(0, _translate("SR830Settings", "Sine Zero Crossing"))
        self.trigger.setItemText(1, _translate("SR830Settings", "TTL Rising Edge"))
        self.trigger.setItemText(2, _translate("SR830Settings", "TTL Falling Edge"))
        self.labelPhase.setText(_translate("SR830Settings", "Phase"))
        self.source.setItemText(0, _translate("SR830Settings", "External"))
        self.source.setItemText(1, _translate("SR830Settings", "Internal"))
        self.frequency.setSuffix(_translate("SR830Settings", " Hz"))
        self.amplitude.setSuffix(_translate("SR830Settings", " Vrms"))
        self.phase.setSuffix(_translate("SR830Settings", "°"))
        self.labelHarmonic.setText(_translate("SR830Settings", "Harmonic"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SR830Settings = QtWidgets.QWidget()
    ui = Ui_SR830Settings()
    ui.setupUi(SR830Settings)
    SR830Settings.show()
    sys.exit(app.exec_())

